apiVersion: v1
kind: ConfigMap
metadata:
  name: akhq-config
  namespace: {{ .Release.Namespace }}
data:
  application.yml: |
    akhq:
      connections:
        aviation:
          properties:
            bootstrap.servers: "{{ .Values.kafka.bootstrapServers }}"
          schema-registry:
            url: "{{ .Values.schemaRegistry.url }}"
            type: confluent
