apiVersion: apps/v1
kind: Deployment
metadata:
  name: akhq
  namespace: {{ .Release.Namespace }}
  labels:
    app: akhq
spec:
  replicas: {{ .Values.replicaCount }}
  selector:
    matchLabels:
      app: akhq
  template:
    metadata:
      labels:
        app: akhq
    spec:
      containers:
      - name: akhq
        image: "{{ .Values.image.repository }}:{{ .Values.image.tag }}"
        imagePullPolicy: {{ .Values.image.pullPolicy }}
        env:
        - name: MICRONAUT_CONFIG_FILES
          value: /app/config/application.yml
        ports:
        - containerPort: 8080
        volumeMounts:
        - name: config
          mountPath: /app/config
        readinessProbe:
          httpGet:
            path: /api/me
            port: 8080
          initialDelaySeconds: 30
          periodSeconds: 10
          failureThreshold: 6
        {{- with .Values.resources }}
        resources:
          {{- toYaml . | nindent 12 }}
        {{- end }}
      volumes:
      - name: config
        configMap:
          name: akhq-config
