name: aviation
version: '1.0.0'
config-version: 2

profile: aviation

model-paths: ["models"]
target-path: "target"
clean-targets: ["target", "dbt_packages"]

models:
  aviation:
    staging:
      +materialized: table
    marts:
      +materialized: table
